---

# for i in 0 1 2; do
#   gcloud compute instances create worker-${i} \
#     --async \
#     --boot-disk-size 200GB \
#     --can-ip-forward \
#     --image-family ubuntu-1604-lts \
#     --image-project ubuntu-os-cloud \
#     --machine-type n1-standard-1 \
#     --metadata pod-cidr=10.200.${i}.0/24 \
#     --private-network-ip 10.240.0.2${i} \
#     --scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
#     --subnet kubernetes \
#     --tags kubernetes-the-hard-way,worker
# done
- name: Create worker instances for kubernetes
  gce:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    zone: "{{ zone }}"
    name: "worker-{{ item }}"
    metadata: '{"pod-cidr": "10.200.{{ item }}.0/24 "}'
    machine_type: n1-standard-1
    image_family: ubuntu-1604-lts
    ip_forward: true
    disk_size: "{{ disk_size }}"
    network: kubernetes-the-hard-way
    subnetwork: kubernetes
    state: present
    tags: kubernetes-the-hard-way,worker
    service_account_permissions:
      - compute-rw
      - storage-ro
      - service-management
      - service-control
      - logging-write
      - monitoring
  register: "workers"
  with_items:
    - 0
    - 1
    - 2


